
# CyberTPR Configuration

# The point around which players can teleport
origin:
  x: 0
  z: 0

# Players can randomly teleport up to this many blocks away from the origin
radius: 5000

# Locations within this many blocks of the origin will be considered unsafe
# This *must* be less than the radius defined above
inner_radius: 500

# Locations will only be considered safe if they're at or above this Y level
# This is to prevent teleporting into open ravines, for example
safe_y: 62

# Locations on these blocks will be considered unsafe (case-insensitive)
# https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
unsafe_blocks:
  - water
  - lava
  - ice
  - packed_ice
  - blue_ice

# Locations within this many blocks of other players will be considered unsafe.
unsafe_nearby_player_radius: 192

# World access
worlds:
  # When true, /tpr will work in all worlds except those listed under blocked
  # When false, /tpr can only be used in the worlds listed under allowed
  allow_by_default: true
  allowed:
    - my allowed world
  blocked:
    - my blocked world

# When true, players can't use /tpr in the corresponding dimension
blocked_dimensions:
  overworld: false
  nether: true
  end: true

# The number of seconds players will need to wait between uses of /tpr
# Players with the cybertpr.cooldown.exempt permission are exempt from cooldowns
# Cooldowns won't persist between server restarts
cooldown: 300

# Try to find a safe location this many times before giving up
# If you preloaded your teleportation area, bunp this up a bunch
max_tries: 5

# Messages
messages:
  reloaded: "&aConfig reloaded!"
  player_only: "&cOnly players can use this command!"
  searching: "&7Searching for a safe spot..."
  search_fail: "&cFailed to find a safe location!"
  teleporting: "&aSending you to &e%0, %1, %2&a..."
  world_blocked: "&cYou can't teleport randomly in this world!"
  dimension_blocked: "&cYou can't teleport randomly in this dimension!"
  cooldown: "&cCooling down! Wait %0 seconds before teleporting again."

# Changing this value will wipe your config!
config_version: 9