main: org.simplecyber.tpr.Plugin
name: CyberTPR
api-version: 1.19
version: 1.2.3
description: Let users teleport to random locations within a set radius of spawn.
commands:
  tpr:
    usage: /tpr
    description: Teleport to a random (safe) location.
    permission: cybertpr.player
  cybertpr:
    usage: /cybertpr [reload]
    description: Manage CyberTPR.
    permission: cybertpr.info
permissions:
  cybertpr.info:
    default: true
  cybertpr.player:
    default: true
  cybertpr.cooldown.exempt:
    default: op
  cybertpr.admin:
    default: op